### ISSUE TITLE
Hardware selling status?

### ISSUE THREAD

**Issue by kungfooman** [OSVR/OSVR-HDK-MCU-Firmware#42]
Hi @rpavlik, you seem to be the one person who keeps the code here alive.

I'm very much aligned with the open source idea and I want to buy a HDK2 for game engine testing (I also learned microcontroller programming etc.).

But I can't find one place to buy one, e.g. this turned into a 404: https://www.razer.com/store/hdk2

Is the hardware side dead? Will there be new hardware? Do you or anyone else know? I need some hardware for testing this...

**Comment by rpavlik** [comment]
The HDK/HDK2 has not been for sale as "new" in years, since probably around 2017-2018, sorry to say. You might have some luck on eBay or other used markets, though the headset cable does tend to wear out over time. It's mostly obsolete at this point, useful primarily for testing or experimentation.

(Yes, I maintained this code while at Sensics and still try to find time to keep it functional now that I'm elsewhere, as I do find utility in having a headset with open-source and thus modifiable firmware. Sensics, the partner of Razer in OSVR behind the software and original hardware designs, is no longer operating. I do not know if Razer, who owns various OSVR IP, has any plans for it, but personally, I consider OpenXR to be the logical successor to OSVR on the software API side, which has achieved adoption far beyond what OSVR ever did.)

Probably the most advanced open source headset community active today would be Project Northstar, which does have a very active community as well as a nonprofit foundation. https://project-north-star.gitbook.io/project-north-star/

The most active open runtime for XR would be Monado, which I am a co-maintainer of: https://monado.freedesktop.org/

Hope this helps! (It is heartwarming to see someone interested in something I put so much heart into, back in the day.)
